// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Example
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SerializableObjectProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Login { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int CountInventory { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float Coin { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"Inventory")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, int> Inventories { get; } = new global::System.Collections.Generic.Dictionary<string, int>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<string> PartyLogins { get; } = new global::System.Collections.Generic.List<string>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
